version: "2.4"
services:
  backend:
    image: openplatform/open-state:${{ github.event.release.tag_name }}
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: open_state
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  redis:
    image: redis:6.0.7
    ports:
      - 6379:6379
