name: Deploy image
description: Deploy project image to server

inputs:

  SSH_KEY:
    description: 'SSH key to access to remote server'
    required: true

  REMOTE_SERVER:
    description: 'Remote server to deploy to'
    required: true
  
  DOCKER_USER_NAME:
    description: 'Docker registry user name'
    required: true
    
  DOCKER_PASSWORD:
    description: 'Docker registry password'
    required: true
    
  DOCKER_IMAGE_TAG:
    description: 'Docker image tag to start'
    required: true

  MONGODB_PASSWORD:
    description: 'Mongo DB password'
    required: true
    
runs:
  using: "composite"
  steps: 
    - run: |
        sudo apt install openssh-client
        sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        eval $(ssh-agent -s)
        echo "${{ SSH_KEY }}" | tr -d '\r' | ssh-add - > /dev/null
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan ${{ REMOTE_SERVER }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        export DOCKER_HOST="ssh://gitlab@${{ REMOTE_SERVER }}"
        export MONGODB_PASSWORD="${{ MONGODB_PASSWORD }}"
        export IMAGE_TAG="${{ DOCKER_IMAGE_TAG }}"
        docker login -u ${{ DOCKER_USER_NAME }} -p ${{ DOCKER_PASSWORD }}
        docker-compose -f docker-compose-server.yml up -d
        docker image ls --filter reference=${{ DOCKER_IMAGE_TAG }} -q | tail -n +4 | xargs --no-run-if-empty docker image rm
      shell: bash
   
