name: Deploy image
description: Deploy project image to server

inputs:

  sshKey:
    description: 'SSH key to connect to server'
    required: true
    
  server:
    description: 'Target server address'
    required: true
  
  dockerUser:
    description: 'DockerHub user name'
    required: true
    
  dockerPassword:
    description: 'DockerHub user password'
    required: true
    
  image:
    description: 'Docker image to deploy'
    required: true
    
runs:
  using: "composite"
  steps: 
    - run: |
        sudo apt install openssh-client
        sudo apt-get install python3-pip
        pip install docker-compose==1.23.2
        eval $(ssh-agent -s)
        echo "${SSHKEY}" | tr -d '\r' | ssh-add - > /dev/null
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan $SERVER >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
      shell: bash
   
