name: Deploy image
description: Deploy project image to server

inputs:

  ssh key:
    description: 'SSH key to connect to server'
    required: true
    
  server:
    description: 'Target server address'
    required: true
  
  docker user:
    description: 'DockerHub user name'
    required: true
    
  docker password:
    description: 'DockerHub user password'
    required: true
    
  image:
    description: 'Docker image to deploy'
    required: true
    
runs:
  using: "composite"
  steps: 
    - run: |
        apk add --no-cache openssh-client
        apk add --no-cache py-pip py-paramiko
        pip install docker-compose==1.23.2
        eval $(ssh-agent -s)
        echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan $SERVER >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
      shell: bash
   
