# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the 2.x.x-REACTIVE branch
on:
  push:
    branches: [ 2.x.x-REACTIVE ]
  pull_request:
    branches: [ 2.x.x-REACTIVE ]

jobs:
  
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    
    env:
    
      MONGODB_HOST: localhost
      MONGODB_PORT: 27017
      MONGODB_DATABASE: open_state
      MONGODB_USERNAME: open_state
      MONGODB_PASSWORD: open_state
      MONGODB_AUTH_DB: admin
    
    
    services:
      
      mongodb:
        image: mongo:3.4.23
        ports: 
          - 27017:27017
           
        env:
          MONGO_INITDB_ROOT_USERNAME: open_state
          MONGO_INITDB_ROOT_PASSWORD:  open_state
          MONGO_INITDB_DATABASE: open_state
    
    steps:
      
      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v2
        
      - id: prepare_java_sdk_11
        name: Prepare Java SDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - id: execute_tests    
        name: Execute tests
        run: ./gradlew check
        
      
     
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [tests]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
